version: "3"
services:
  sonarqube:
    image: sonarqube
    restart: unless-stopped
    environment:
      - SONAR_JDBC_USERNAME=sonarqube
      - SONAR_JDBC_PASSWORD=sonarpass
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - sonarqube_conf_1:/opt/sonarqube/conf
      - sonarqube_data_1:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarpass
      - POSTGRES_DB=sonarqube
    volumes:
      - sonarqube_db_1:/var/lib/postgresql
      - postgresql_data_1:/var/lib/postgresql/data

  nginx:
    build:
      context: .
      dockerfile: nginx-conf/Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    # volumes:
    #   - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sonarqube


volumes:
  postgresql_data_1:
  sonarqube_bundled-plugins:
  sonarqube_conf_1:
  sonarqube_data_1:
  sonarqube_db_1:
  sonarqube_extensions:

